version: "3.11"

services:
  frontend:
    build: ./web-app # build the Docker image from the Dockerfile in the front-end directory
    ports:
      - 3000:3000 # map port 3000 of host machine to port 3000 of container
    depends_on:
      - backend
    command: python app.py # command to start up the front-end once the container is up and running

  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - type: bind
        source: ./data
        target: /data/db

  backend:
    build: ./machine-learning-client
  
