name: Deploy to DigitalOcean

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: CICD
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{secrets.SSH_HOST_RQ}}
        key: ${{secrets.SSH_KEY_RQ}}
        username: ${{secrets.SSH_USERNAME_RQ}}

        script: |
          mkdir test
          cd test
          git clone git@github.com:software-students-fall2023/4-containerized-app-exercise-rizzballs.git
          echo 'deploy success'


