name: check lint and format
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y portaudio19-dev
<<<<<<< HEAD
=======
      - name: Install dependencies
>>>>>>> 7f47eac (tring to get workflow)
        if: ${{ hashFiles('**/*.py') != '' }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv sync --dev --python $(which python)
          pipenv shell --fancy --python $(which python)
      - name: Lint with pylint
        if: ${{ hashFiles('**/*.py') != '' }}
        run: |
          pipenv run pylint **/*.py
      - name: Format with black
        if: ${{ hashFiles('**/*.py') != '' }}
        run: |
          pipenv run black --diff --check .
