name: ML Tests

run-name: ${{ github.actor }} is automating using Github Actions

on: 
    push:
      branches: [main, master]
    pull_request:
      branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
        pipenv install -r requirements.txt 
        pipenv sync

    - name: Run tests
      run: |
        cd machine-learning-client/tests
        pipenv run pytest --cov=machine_learning_client.py ml_tests.py